### ISSUE TITLE
Xoá mèo/sản phẩm. tạo func(mã, database)

### ISSUE THREAD

**Issue by TuanChill** [TuanChill/Project-C#6]
![image](https://user-images.githubusercontent.com/93763718/201873510-4fb487ad-fe6b-4260-9fc8-8db0d26e9fe6.png)

Dùng cái func tìm kiếm dùng
@DurkYerunz @nghtamm

**Comment by ghost** [comment]
đéo làm

**Comment by DurkYerunz** [comment]
đéo làm
